### ISSUE TITLE
Debug crashes on D command

### ISSUE THREAD

**Issue by ecm-pushbx** [buricco/doslite#1]
While importing your (only) source revision of Debug into an hg repo based on the MS-DOS v2 release, I noticed in the diff (viewed using `hg d --text -r 30:31 --ignore-all-space | diffrr | less -Rr`) that you accidentally deleted a bit of code from debcom1.asm that was in an `else` clause of a build conditional. Testing the D command it appeared to crash with this omission. Here's the diff:

```
--- a/debcom1.asm	Mon Aug 01 21:31:45 2022 +0200
+++ b/debcom1.asm	Mon Aug 01 21:45:07 2022 +0200
@@ -172,6 +172,17 @@
           mov       ax,si               ; Current dump address
           mov       si,dx               ; ASCII dump address
           sub       ax,dx               ; AX=length of ASCII dump
+
+        mov     cx,si                   ; get starting point
+        dec     cx
+        and     cx,0fh
+        inc     cx
+        and     cx,0fh
+        add     cx,3                    ; we have the correct number to tab
+        push    ax                      ; save count
+        call    tab
+        pop     cx                      ; get count back
+
 ascdmp:   lodsb                         ; Get ASCII byte to dump
           and       al,7fh              ; ASCII uses 7 bits
           cmp       al,7fh              ; Don't try to print RUBOUT
```

And here's my revision of this fix in my hg repo: https://hg.pushbx.org/ecm/msdebug/rev/c26d0b328b2f

**Comment by buricco** [comment]
Diff should be applied now. No idea how that happened.

**Comment by buricco** [comment]
Ah.  I was cleaning up the ZIBO ifdef, that explains it 🤪

**Comment by ecm-pushbx** [comment]
Fixed in https://github.com/buricco/doslite/commit/d3c583dfd5b0a675b4805f404c672e5834d00e6c
