### ISSUE TITLE
Two Debug bugfixes and ORG directive for line assembler

### ISSUE THREAD

**Issue by ecm-pushbx** [buricco/doslite#2]
During modding your Debug sources I found that segment registers were not accepted for specifying segments in address parameters, because you accidentally made a capital `S` into a small `s` (within quotemarks). Fix in https://hg.pushbx.org/ecm/msdebug/rev/e9780e9e9feb

Investigating the source of this error I found a second error of the same type (capital `F` to small `f` in quotemarks), which prevented the `R F` command from working. Fix in https://hg.pushbx.org/ecm/msdebug/rev/1fa1c5321233

Finally, I [added](https://hg.pushbx.org/ecm/msdebug/rev/4f91fac433eb) an `org` directive to the assembler. For bonus points I [extended the debugger's error handling](https://hg.pushbx.org/ecm/msdebug/rev/deffd61c730d) so `org` errors will return to the line assembler prompt instead of the debugger main prompt. (The `debug.exe` program I found, which checks for DOS v5.00, doesn't behave sensibly on `org` errors, taking them as bogus origin settings instead. However, it does return to the line assembler prompt regardless.)

**Comment by buricco** [comment]
Looks like I was a little heavyhanded when crushing case.

Applied all suggestions in most recent push.

**Comment by ecm-pushbx** [comment]
Applied in https://github.com/buricco/doslite/commit/a39f285937403f4acb1189391880eb2642b6ead9
